def gv
pipeline {
    agent any
    tools {
        maven 'maven'
    }
    stages {
        stage("init") {
            steps {
                script {
                    gv= load "script.groovy"
                }
            }
        }
        stage("buildJar") {
            steps {
                script {
                    gv.buildJar()
                }
            }
        }
        stage("buildImage") {
            steps {
                script {
                    gv.buildImage()
                }
            }
        }
        stage("pushImage") {
            steps {
                script {
                    gv.pushImage()
                }
            }
        }
    }
}


