apiVersion: apps/v1
kind: Deployment
metadata:
 name: mosquitto-deployment
 labels:
  app: mosquitto
spec:
 replicas: 1
 selector:
  matchLabels:
   app: mosquitto
 template:
  metadata:
   labels:
    app: mosquitto
  spec:
   containers:
   - name: mosquitto
     image: eclipse-mosquitto
     ports:
     - containerPort: 1883
     volumeMounts:
      - name: mosquitto-configmap
        mountPath: /mosquitto/config
      - name: mosquitto-secret
        mountPath: /mosquitto/secret
        readOnly: true  
   volumes:
    - name: mosquitto-configmap
      configMap:
       name: mosquitto-configmap-volume
    - name: mosquitto-secret
      secret:
       secretName: mosquitto-secret-volume

   
