apiVersion: apps/v1
kind: Deployment
metadata:
 name: java-maven-app
 labels:
  app: java-maven-app
spec:
 replicas: 2
 selector:
  matchLabels:
    app: java-maven-app
 template:
  metadata:
   labels:
     app: java-maven-app
  spec:
   imagePullSecrets:
   - name: ecr-auth-secret
   containers:
   - name: java-maven-app
     image: $REPO_NAME:$IMAGE_TAG
     imagePullPolicy: Always
     ports:
     - containerPort: 8080
